from app.services.trade_store import upsert_name_mapping


COMMON_NAME_MAPPINGS = [
    {
        "raw_name": "USD 애플",
        "normalized_name": "애플",
        "ticker": "AAPL",
        "canonical_name": "Apple Inc.",
        "exchange": "NASDAQ",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 유나이티드헬스 그룹",
        "normalized_name": "유나이티드헬스 그룹",
        "ticker": "UNH",
        "canonical_name": "UnitedHealth Group Inc.",
        "exchange": "NYSE",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD Direxion 미국 반도체 3X ETF",
        "normalized_name": "Direxion 미국 반도체 3X ETF",
        "ticker": "SOXL",
        "canonical_name": "Direxion Daily Semiconductor Bull 3X Shares",
        "exchange": "NYSEARCA",
        "market": "US",
        "asset_type": "etf",
        "currency": "USD",
    },
    {
        "raw_name": "USD 이더리움 2X ETF",
        "normalized_name": "이더리움 2X ETF",
        "ticker": "ETHU",
        "canonical_name": "2x Ether ETF",
        "exchange": "NYSEARCA",
        "market": "US",
        "asset_type": "etf",
        "currency": "USD",
    },
    {
        "raw_name": "USD 버티브 홀딩스",
        "normalized_name": "버티브 홀딩스",
        "ticker": "VRT",
        "canonical_name": "Vertiv Holdings Co",
        "exchange": "NYSE",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 마이크론 테크놀로지",
        "normalized_name": "마이크론 테크놀로지",
        "ticker": "MU",
        "canonical_name": "Micron Technology Inc.",
        "exchange": "NASDAQ",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 아리스타 네트웍스",
        "normalized_name": "아리스타 네트웍스",
        "ticker": "ANET",
        "canonical_name": "Arista Networks Inc.",
        "exchange": "NYSE",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 셰니어 에너지",
        "normalized_name": "셰니어 에너지",
        "ticker": "LNG",
        "canonical_name": "Cheniere Energy Inc.",
        "exchange": "NYSE",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 엔비디아",
        "normalized_name": "엔비디아",
        "ticker": "NVDA",
        "canonical_name": "NVIDIA Corporation",
        "exchange": "NASDAQ",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 로켓 랩",
        "normalized_name": "로켓 랩",
        "ticker": "RKLB",
        "canonical_name": "Rocket Lab USA Inc.",
        "exchange": "NASDAQ",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 코히런트",
        "normalized_name": "코히런트",
        "ticker": "COHR",
        "canonical_name": "Coherent Corp.",
        "exchange": "NYSE",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 마이크로소프트",
        "normalized_name": "마이크로소프트",
        "ticker": "MSFT",
        "canonical_name": "Microsoft Corporation",
        "exchange": "NASDAQ",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 아이온큐",
        "normalized_name": "아이온큐",
        "ticker": "IONQ",
        "canonical_name": "IonQ Inc.",
        "exchange": "NYSE",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 알파벳 Class C",
        "normalized_name": "알파벳 Class C",
        "ticker": "GOOG",
        "canonical_name": "Alphabet Inc. Class C",
        "exchange": "NASDAQ",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD 지브라 테크놀로지스",
        "normalized_name": "지브라 테크놀로지스",
        "ticker": "ZBRA",
        "canonical_name": "Zebra Technologies Corporation",
        "exchange": "NASDAQ",
        "market": "US",
        "asset_type": "stock",
        "currency": "USD",
    },
    {
        "raw_name": "USD iShares 20+ Year 미국 국채 ETF",
        "normalized_name": "iShares 20+ Year 미국 국채 ETF",
        "ticker": "TLT",
        "canonical_name": "iShares 20+ Year Treasury Bond ETF",
        "exchange": "NASDAQ",
        "market": "US",
        "asset_type": "etf",
        "currency": "USD",
    },
    {
        "raw_name": "TIGER KRX금현물",
        "normalized_name": "TIGER KRX금현물",
        "ticker": "411060",
        "canonical_name": "TIGER KRX금현물",
        "exchange": "KRX",
        "market": "KR",
        "asset_type": "etf",
        "currency": "KRW",
    },
    {
        "raw_name": "현대차",
        "normalized_name": "현대차",
        "ticker": "005380",
        "canonical_name": "현대자동차",
        "exchange": "KRX",
        "market": "KR",
        "asset_type": "stock",
        "currency": "KRW",
    },
]


def seed_name_mappings() -> None:
    for item in COMMON_NAME_MAPPINGS:
        upsert_name_mapping(
            raw_name=item["raw_name"],
            normalized_name=item["normalized_name"],
            ticker=item["ticker"],
            canonical_name=item.get("canonical_name"),
            exchange=item.get("exchange"),
            market=item.get("market"),
            asset_type=item.get("asset_type"),
            currency=item.get("currency"),
            source="seed",
            confidence=1.0,
            mapping_status="confirmed",
        )
